# Generated by Django 2.2.2 on 2019-07-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('event', models.TextField()),
                ('score', models.IntegerField()),
            ],
        ),
    ]
