# Generated by Django 2.2.3 on 2019-08-12 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_scores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scores',
            options={'verbose_name_plural': 'Scores'},
        ),
        migrations.AddField(
            model_name='scores',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
