# Generated by Django 2.2.3 on 2019-08-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_scores_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scores',
            options={'verbose_name_plural': 'Scores'},
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='scores',
            name='firebase',
            field=models.BooleanField(default=False),
        ),
    ]
