# Generated by Django 2.2.3 on 2019-08-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_scores_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.TextField()),
                ('participant1', models.TextField()),
                ('tickedid', models.TextField()),
            ],
        ),
    ]
